# Generated by Django 4.2.4 on 2023-08-15 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_scrapemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapemodel',
            name='url',
            field=models.URLField(max_length=1000),
        ),
    ]
